import { storeDocumentationKinds } from "../../db/monday-board-spec";
import type {
  FileRecord,
  MaintenanceRequest,
  StoreRecord,
} from "./types";

/*
 * `contractorId` is null on every row here, and that is the correct value
 * rather than a gap waiting to be filled.
 *
 * These are the demo fixtures the portal falls back to when a workspace has no
 * register of its own. A canonical id only means something against real
 * `contractors` rows, and in the situation that puts these on screen there are
 * none — so the screens match them to the synthesised fallback roster by name,
 * exactly as they always have. See the note on `MaintenanceRequest.contractorId`.
 */
export const maintenanceRequests: MaintenanceRequest[] = [
  {
    id: "MN-1048",
    source: "Portal form",
    title: "Main CCTV camera offline",
    description:
      "The main camera has stopped functioning and covers the full shop floor. The site needs an urgent engineer visit.",
    location: "Bristol Cabot Circus",
    siteId: "store-bristol",
    requester: "Sample Manager A",
    contact: "+44 7700 900000",
    category: "CCTV",
    engineer: "Electrician",
    tier: 1,
    priority: "Urgent",
    stage: "Attention",
    status: "Waiting for decisions",
    contractor: "UK Safety",
    contractorId: null,
    assignee: "Sample Coordinator A",
    requestedAt: "2026-07-29T08:20:00.000Z",
    dueAt: "2026-07-29T16:00:00.000Z",
    completedAt: null,
    nextUpdateAt: "2026-07-29T13:30:00.000Z",
    cost: null,
    attachmentCount: 2,
    commentCount: 4,
  },
  {
    id: "MN-1047",
    source: "Portal form",
    title: "Cabinet lighting flickering",
    description:
      "Two display cabinet lights are flickering intermittently near the front counter.",
    location: "Sheffield Meadowhall",
    siteId: "store-meadowhall",
    requester: "Sample Manager B",
    contact: "+44 7700 900001",
    category: "Lighting",
    engineer: "Electrician",
    tier: 2,
    priority: "Urgent",
    stage: "Incoming",
    status: "Awaiting Landlord Approval",
    contractor: "Saed Electrical",
    contractorId: null,
    assignee: null,
    requestedAt: "2026-07-28T11:40:00.000Z",
    dueAt: "2026-07-30T17:00:00.000Z",
    completedAt: null,
    nextUpdateAt: "2026-07-29T15:00:00.000Z",
    cost: 320,
    attachmentCount: 3,
    commentCount: 2,
  },
  {
    id: "MN-1046",
    source: "Portal form",
    title: "Cupboard door requires adjustment",
    description:
      "The rear cupboard door no longer closes cleanly and may damage the hinge.",
    location: "Sheffield Meadowhall",
    siteId: "store-meadowhall",
    requester: "Sample Manager B",
    contact: "+44 7700 900002",
    category: "Joinery",
    engineer: "Handyman",
    tier: 3,
    priority: "Low",
    stage: "Incoming",
    status: "Pending Approval",
    contractor: null,
    contractorId: null,
    assignee: "Sample Coordinator B",
    requestedAt: "2026-07-28T09:15:00.000Z",
    dueAt: "2026-08-04T17:00:00.000Z",
    completedAt: null,
    nextUpdateAt: "2026-07-30T10:00:00.000Z",
    cost: null,
    attachmentCount: 1,
    commentCount: 1,
  },
  {
    id: "MN-1045",
    source: "Portal form",
    title: "TV display not responding",
    description:
      "The window display screen powers on, but the remote cannot select content or change inputs.",
    location: "Bluewater",
    siteId: "store-bluewater",
    requester: "Sample Manager C",
    contact: "+44 7700 900003",
    category: "Digital display",
    engineer: "Electrician",
    tier: 2,
    priority: "Medium",
    stage: "Incoming",
    status: "Job Scheduled",
    contractor: "Vision AV",
    contractorId: null,
    assignee: "Sample Coordinator A",
    requestedAt: "2026-07-27T15:05:00.000Z",
    dueAt: "2026-07-31T12:00:00.000Z",
    completedAt: null,
    nextUpdateAt: "2026-07-30T09:00:00.000Z",
    cost: 185,
    attachmentCount: 2,
    commentCount: 3,
  },
  {
    id: "MN-1044",
    source: "Manual",
    title: "Replace broken entrance glass",
    description:
      "Lower entrance panel is cracked. Area is safe and the replacement glass has been ordered.",
    location: "Solihull",
    siteId: "store-solihull",
    requester: "Mall Operations",
    contact: "+44 121 555 0188",
    category: "Glass",
    engineer: "Specialist",
    tier: 2,
    priority: "Urgent",
    stage: "Booked",
    status: "Job Scheduled",
    contractor: "Midlands Glass",
    contractorId: null,
    assignee: "Sample Coordinator B",
    requestedAt: "2026-07-21T10:20:00.000Z",
    dueAt: "2026-07-31T09:00:00.000Z",
    completedAt: null,
    nextUpdateAt: "2026-07-30T16:00:00.000Z",
    cost: 1142,
    attachmentCount: 4,
    commentCount: 5,
  },
  {
    id: "MN-1043",
    source: "Manual",
    title: "Fixed wire testing (EICR)",
    description:
      "Planned fixed wire testing visit and remedial report for the store.",
    location: "Bristol Cabot Circus",
    siteId: "store-bristol",
    requester: "Facilities Team",
    contact: "+44 20 7946 0143",
    category: "Compliance",
    engineer: "Electrician",
    tier: 4,
    priority: "Urgent",
    stage: "Booked",
    status: "Third Party Delay",
    contractor: "UK Safety",
    contractorId: null,
    assignee: "Sample Coordinator A",
    requestedAt: "2026-06-25T09:00:00.000Z",
    dueAt: "2026-08-02T17:00:00.000Z",
    completedAt: null,
    nextUpdateAt: "2026-07-31T12:00:00.000Z",
    cost: 680,
    attachmentCount: 6,
    commentCount: 8,
  },
  {
    id: "MN-1042",
    source: "Manual",
    title: "Replace signboard lettering",
    description:
      "Replacement letters have arrived and the installation invoice is awaiting payment.",
    location: "Reading",
    siteId: "store-reading",
    requester: "Sample Manager D",
    contact: "+44 7700 900004",
    category: "Signage",
    engineer: "Handyman",
    tier: 3,
    priority: "Urgent",
    stage: "Booked",
    status: "Waiting for payment",
    contractor: "Johnny Signage",
    contractorId: null,
    assignee: "Sample Coordinator B",
    requestedAt: "2026-07-01T08:00:00.000Z",
    dueAt: "2026-07-30T13:00:00.000Z",
    completedAt: null,
    nextUpdateAt: "2026-07-29T14:00:00.000Z",
    cost: 460,
    attachmentCount: 3,
    commentCount: 6,
  },
  {
    id: "MN-1041",
    source: "Portal form",
    title: "Front cabinet lighting repaired",
    description:
      "Replaced failed LED driver and tested the full display cabinet lighting circuit.",
    location: "Wood Green",
    siteId: "store-woodgreen",
    requester: "Sample Manager E",
    contact: "+44 7700 900005",
    category: "Lighting",
    engineer: "Electrician",
    tier: 2,
    priority: "Medium",
    stage: "Completed",
    status: "Job Completed",
    contractor: "Saed Electrical",
    contractorId: null,
    assignee: "Sample Coordinator A",
    requestedAt: "2026-07-10T10:00:00.000Z",
    dueAt: "2026-07-14T15:00:00.000Z",
    completedAt: "2026-07-14T14:35:00.000Z",
    nextUpdateAt: null,
    cost: 265,
    attachmentCount: 5,
    commentCount: 2,
  },
  {
    id: "MN-1040",
    source: "Portal form",
    title: "Air-conditioning temperature issue",
    description:
      "Store temperature remains above target and the rear unit is making an intermittent noise.",
    location: "Aldgate",
    siteId: "store-aldgate",
    requester: "Sample Manager F",
    contact: "+44 7700 900006",
    category: "HVAC",
    engineer: "HVAC",
    tier: 1,
    priority: "Urgent",
    stage: "Attention",
    status: "Job In Progress",
    contractor: "Climate Response",
    contractorId: null,
    assignee: "Sample Coordinator A",
    requestedAt: "2026-07-26T07:30:00.000Z",
    dueAt: "2026-07-29T12:00:00.000Z",
    completedAt: null,
    nextUpdateAt: "2026-07-29T11:30:00.000Z",
    cost: 540,
    attachmentCount: 2,
    commentCount: 7,
  },
];

const compliant = (
  kind: string,
  expiry: string,
  fileCount = 1,
) => ({ kind, state: "Compliant" as const, expiry, fileCount });

const missing = (kind: string) => ({
  kind,
  state: "Missing" as const,
  expiry: null,
  fileCount: 0,
});

export const stores: StoreRecord[] = [
  {
    id: "store-aldgate",
    name: "Aldgate",
    type: "Inline",
    region: "UK",
    lifecycle: "Current",
    status: "active",
    address: "Unit 5, Whitechapel Technology Centre, London E1 7LE",
    manager: "Sample Manager F",
    openRequests: 1,
    annualBudgetPence: null,
    compliance: [
      compliant("PAT Test", "2026-11-24"),
      compliant("Fire Alarm", "2027-04-12"),
      compliant("Emergency Lighting", "2027-04-12"),
      missing("Water Hygiene"),
    ],
  },
  {
    id: "store-stratford",
    name: "Westfield Stratford",
    type: "Kiosk",
    region: "UK",
    lifecycle: "Current",
    status: "active",
    address: "Kiosk K29, Westfield Stratford City, London E20 1EJ",
    manager: "Sample Manager G",
    openRequests: 0,
    annualBudgetPence: null,
    compliance: [
      compliant("PAT Test", "2027-05-10", 3),
      compliant("Electrical Wiring", "2031-07-10"),
      { kind: "Fire Alarm", state: "Not required", expiry: null, fileCount: 0 },
      { kind: "Water Hygiene", state: "Not required", expiry: null, fileCount: 0 },
    ],
  },
  {
    id: "store-woodgreen",
    name: "Wood Green",
    type: "Kiosk",
    region: "UK",
    lifecycle: "Current",
    status: "active",
    address: "Commercial Site 4, The Mall Wood Green, London N22 6YQ",
    manager: "Sample Manager E",
    openRequests: 0,
    annualBudgetPence: null,
    compliance: [
      compliant("PAT Test", "2026-11-23"),
      compliant("Fire Alarm", "2027-01-18"),
      missing("Emergency Lighting"),
      compliant("Water Hygiene", "2027-02-08"),
    ],
  },
  {
    id: "store-brentcross",
    name: "Brent Cross",
    type: "Kiosk",
    region: "UK",
    lifecycle: "Current",
    status: "active",
    address: "Kiosk 5, Brent Cross Shopping Centre, London NW4 3FP",
    manager: "Sample Manager H",
    openRequests: 0,
    annualBudgetPence: null,
    compliance: [
      { kind: "PAT Test", state: "Expiring soon", expiry: "2026-11-03", fileCount: 1 },
      compliant("Fire Alarm", "2027-03-20"),
      compliant("Emergency Lighting", "2027-03-20"),
      missing("Water Hygiene"),
    ],
  },
  {
    id: "store-solihull",
    name: "Solihull",
    type: "Inline",
    region: "UK",
    lifecycle: "Current",
    status: "active",
    address: "36A The Broadway, Touchwood, Solihull B91 3QG",
    manager: "Sample Manager I",
    openRequests: 1,
    annualBudgetPence: null,
    compliance: [
      { kind: "PAT Test", state: "Expired", expiry: "2026-07-20", fileCount: 4 },
      compliant("Fire Alarm", "2027-03-04"),
      compliant("Emergency Lighting", "2027-03-04"),
      compliant("Water Hygiene", "2027-05-16"),
    ],
  },
  {
    id: "store-reading",
    name: "The Oracle Centre — Reading",
    type: "Kiosk",
    region: "UK",
    lifecycle: "Current",
    status: "active",
    address: "Kiosk 19, Oracle Shopping Centre, Reading RG1 2AG",
    manager: "Sample Manager D",
    openRequests: 1,
    annualBudgetPence: null,
    compliance: [
      compliant("PAT Test", "2026-11-22", 3),
      compliant("Fire Alarm", "2027-02-14"),
      compliant("Emergency Lighting", "2027-02-14"),
      compliant("Water Hygiene", "2027-05-01"),
    ],
  },
  {
    id: "store-bluewater",
    name: "Bluewater",
    type: "Inline",
    region: "UK",
    lifecycle: "Current",
    status: "active",
    address: "Unit WVLO7/WVLO8, Guildhall Mall, Greenhithe DA9 9ST",
    manager: "Sample Manager C",
    openRequests: 1,
    annualBudgetPence: null,
    compliance: [
      compliant("PAT Test", "2027-06-28", 4),
      compliant("Fire Alarm", "2027-06-28"),
      compliant("Emergency Lighting", "2027-06-28"),
      compliant("Water Hygiene", "2027-06-28"),
    ],
  },
  {
    id: "store-bristol",
    name: "Bristol Cabot Circus",
    type: "Kiosk",
    region: "UK",
    lifecycle: "Current",
    status: "active",
    address: "Kiosk 14, Cabot Circus, Bristol BS1 3BD",
    manager: "Sample Manager A",
    openRequests: 2,
    annualBudgetPence: null,
    compliance: [
      compliant("PAT Test", "2027-01-14"),
      { kind: "Fire Alarm", state: "Expiring soon", expiry: "2026-08-18", fileCount: 1 },
      compliant("Emergency Lighting", "2027-02-19"),
      compliant("Water Hygiene", "2027-04-10"),
    ],
  },
  {
    id: "store-meadowhall",
    name: "Sheffield Meadowhall",
    type: "Kiosk",
    region: "UK",
    lifecycle: "Current",
    status: "active",
    address: "Kiosk H2, Meadowhall Centre, Sheffield S9 1EP",
    manager: "Sample Manager B",
    openRequests: 2,
    annualBudgetPence: null,
    compliance: [
      compliant("PAT Test", "2027-03-12"),
      compliant("Fire Alarm", "2027-03-12"),
      missing("Emergency Lighting"),
      compliant("Water Hygiene", "2027-05-07"),
    ],
  },
  {
    id: "store-hq",
    name: "HQ — The Loom",
    type: "Office",
    region: "Other",
    lifecycle: "Current",
    status: "other",
    address: "The Loom, 14 Gower's Walk, London E1 8PY",
    manager: "Operations Team",
    openRequests: 0,
    annualBudgetPence: null,
    compliance: [
      compliant("PAT Test", "2027-06-05"),
      compliant("Fire Alarm", "2027-06-05"),
      compliant("Emergency Lighting", "2027-06-05"),
      compliant("Water Hygiene", "2027-06-05"),
    ],
  },
];

/**
 * Every site carries all twelve Store Documentation requirements.
 *
 * The board has a column per requirement, so a store with no PLI on file still
 * has a visibly empty PLI cell. The seed listed only the three or four
 * requirements each store happened to hold, so the register reported "38
 * records" against a portfolio that actually owes 12 × 11 = 132, and a missing
 * sprinkler certificate was indistinguishable from one nobody had asked for.
 *
 * Anything already seeded is left exactly as it is; the rest fill in as
 * Missing, which is what the board shows for an empty file cell.
 */
for (const store of stores) {
  const held = new Set(store.compliance.map((item) => item.kind));
  for (const kind of storeDocumentationKinds) {
    if (held.has(kind)) continue;
    store.compliance.push(missing(kind));
  }
  store.compliance.sort(
    (left, right) =>
      storeDocumentationKinds.indexOf(left.kind) -
      storeDocumentationKinds.indexOf(right.kind),
  );
}

export const files: FileRecord[] = [
  {
    id: "DOC-2801",
    name: "EICR_Bristol_Cabot_Circus.pdf",
    kind: "Electrical certificate",
    site: "Bristol Cabot Circus",
    requestId: "MN-1043",
    uploadedAt: "2026-07-28T12:12:00.000Z",
    size: "2.4 MB",
    status: "Current",
  },
  {
    id: "DOC-2800",
    name: "cabinet-lighting-before.jpg",
    kind: "Maintenance photo",
    site: "Sheffield Meadowhall",
    requestId: "MN-1047",
    uploadedAt: "2026-07-28T11:42:00.000Z",
    size: "1.8 MB",
    status: "Current",
  },
  {
    id: "DOC-2799",
    name: "landlord-approval-email.pdf",
    kind: "Approval",
    site: "Sheffield Meadowhall",
    requestId: "MN-1047",
    uploadedAt: "2026-07-28T12:06:00.000Z",
    size: "420 KB",
    status: "Current",
  },
  {
    id: "DOC-2798",
    name: "PAT_Solihull_2025.pdf",
    kind: "PAT certificate",
    site: "Solihull",
    requestId: null,
    uploadedAt: "2025-11-01T09:30:00.000Z",
    size: "3.1 MB",
    status: "Archived",
  },
  {
    id: "DOC-2797",
    name: "store-drawing-westfield-stratford.pdf",
    kind: "Store drawing",
    site: "Westfield Stratford",
    requestId: null,
    uploadedAt: "2026-06-15T16:30:00.000Z",
    size: "8.9 MB",
    status: "Current",
  },
  {
    id: "DOC-2796",
    name: "fire-alarm-bristol.pdf",
    kind: "Fire alarm report",
    site: "Bristol Cabot Circus",
    requestId: null,
    uploadedAt: "2025-08-18T09:00:00.000Z",
    size: "1.2 MB",
    status: "Expiring soon",
  },
];

