import { chromium } from "playwright";
const b = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium-1194/chrome-linux/chrome", args:["--no-sandbox"] });
const p = await (await b.newContext({viewport:{width:1500,height:1050}})).newPage();
const errs=[]; p.on("pageerror",e=>errs.push(String(e))); p.on("console",m=>{if(m.type()==="error")errs.push(m.text())});
await p.goto("http://localhost:5173/dashboard/jobs", { waitUntil:"networkidle" });
await p.waitForTimeout(7000);
await p.locator("button", { hasText: "Manage data" }).first().click({ timeout: 20000 });
await p.waitForTimeout(1800);
await p.locator('[role="tab"]', { hasText: "Import" }).click();
await p.waitForTimeout(1200);
await p.locator('.monday-import input[type="file"]').setInputFiles("/tmp/monday-maintenance-export.xlsx");
await p.waitForTimeout(600);
await p.locator(".monday-import button", { hasText: "Preview" }).click();
await p.waitForTimeout(12000);
console.log("stats:\n" + (await p.locator(".monday-import__stats").innerText().catch(()=> "none")));
console.log("sections:", JSON.stringify(await p.locator(".monday-import__preview section h4").allTextContents()));
console.log("sample rows:", await p.locator(".monday-import__sample tbody tr").count());
await p.screenshot({ path:"/home/claude/shots-imp/import.png" });
console.log("ERRORS:", JSON.stringify([...new Set(errs)].slice(0,6)));
await b.close();
