/**
 * Which rendered widths exist for each approved v3 asset.
 *
 * Generated by scripts/install-assets-v3.mjs from the supplied originals — do
 * not edit by hand. Sources are never upscaled, so an image narrower than a
 * listed width simply has no variant at it; advertising one would make the
 * browser fetch a blurrier file than the original it could have had.
 */
export type AssetEntry = {
  /** Rendered widths that actually exist, for the srcset. */
  widths: number[];
  /** The supplied original's own size, so the box reserved matches the picture. */
  width: number;
  height: number;
};

export const assetWidths: Record<string, AssetEntry> = {
  "/assets/audience/who-we-help-retail-chains.png": {
    "widths": [
      480,
      960,
      1400
    ],
    "width": 1672,
    "height": 941
  },
  "/assets/audience/who-we-help-shopping-centre-kiosks.png": {
    "widths": [
      480,
      960,
      1400
    ],
    "width": 1672,
    "height": 941
  },
  "/assets/audience/who-we-help-franchise-groups.png": {
    "widths": [
      480,
      960,
      1400
    ],
    "width": 1672,
    "height": 941
  },
  "/assets/audience/who-we-help-clinics-wellness.png": {
    "widths": [
      480,
      960,
      1400
    ],
    "width": 1672,
    "height": 941
  },
  "/assets/audience/who-we-help-gyms-studios.png": {
    "widths": [
      480,
      960,
      1400
    ],
    "width": 1672,
    "height": 941
  },
  "/assets/audience/who-we-help-commercial-offices.png": {
    "widths": [
      480,
      960,
      1400
    ],
    "width": 1672,
    "height": 941
  },
  "/assets/workflow/how-it-works-01-report-v3.jpg": {
    "widths": [
      480,
      960,
      1240
    ],
    "width": 1240,
    "height": 531
  },
  "/assets/workflow/how-it-works-02-triage-v3.png": {
    "widths": [
      480,
      960,
      1400
    ],
    "width": 1672,
    "height": 941
  },
  "/assets/workflow/how-it-works-03-approve-v3.png": {
    "widths": [
      480,
      960,
      1400
    ],
    "width": 1672,
    "height": 941
  },
  "/assets/workflow/how-it-works-04-assign-v3.png": {
    "widths": [
      480,
      960,
      1400
    ],
    "width": 1672,
    "height": 941
  },
  "/assets/workflow/how-it-works-05-attend-v3.png": {
    "widths": [
      480,
      960,
      1400
    ],
    "width": 1672,
    "height": 941
  },
  "/assets/workflow/how-it-works-06-verify-v3.png": {
    "widths": [
      480,
      960,
      1400
    ],
    "width": 1672,
    "height": 941
  },
  "/assets/workflow/how-it-works-07-reporting-v3.png": {
    "widths": [
      480,
      960,
      1400
    ],
    "width": 1672,
    "height": 941
  }
};
