/**
 * Generated by convert-images.mjs — do not edit by hand.
 *
 * Which rendered widths actually exist for each photograph. Sources are never
 * upscaled, so a 900px original has no 1600px variant; advertising one in a
 * srcset would make the browser request a file that is not there.
 */
export const photoWidths: Record<string, number[]> = {
  "dashboard-compliance": [
    480,
    960,
    1600
  ],
  "dashboard-jobs": [
    480,
    960,
    1600
  ],
  "dashboard-overview": [
    480,
    960,
    1600
  ],
  "dashboard-spend": [
    480,
    960,
    1600
  ],
  "evidence-closeout": [
    480,
    960
  ],
  "hero-london-maintenance": [
    480,
    960,
    1600
  ],
  "hero-maintenance-v4": [
    480,
    960,
    1600,
    1916
  ],
  "social-card": [
    480,
    960
  ],
  "trade-doors": [
    480
  ],
  "trade-drainage": [
    480
  ],
  "trade-electrical": [
    480
  ],
  "trade-fabric": [
    480
  ],
  "trade-glazing": [
    480
  ],
  "trade-hvac": [
    480
  ],
  "trade-leaks": [
    480
  ],
  "trade-signage": [
    480
  ],
  "workflow-1-report": [
    480,
    960
  ],
  "workflow-2-triage": [
    480,
    960
  ],
  "workflow-3-approve": [
    480,
    960
  ],
  "workflow-4-assign": [
    480,
    960
  ],
  "workflow-5-attend": [
    480,
    960
  ],
  "workflow-6-verify": [
    480,
    960
  ],
  "workflow-7-report": [
    480,
    960
  ]
};
