/**
 * A `CombinedReportPayload` with something wrong with it on purpose.
 *
 * WHAT THIS IS FOR
 *
 * The renderers were written before the engine and the API routes existed, and
 * this is what they were written against. It is not a demo and nothing that
 * ships imports it: the preview, the three exporters and the export routes all
 * take a payload from their caller, and this module is reachable only from
 * `tests/`.
 *
 * WHY IT IS DELIBERATELY UGLY
 *
 * A tidy fixture proves a renderer can draw a tidy fixture. Every awkward shape
 * the contract explicitly permits is present here instead, because each of them
 * is a way a real export breaks in front of a client:
 *
 *  - `singleFeePence: null` with mixed site fees, so the KPI card must say
 *    "Average Site Fee" and not invent a single one.
 *  - An EXCLUDED line, with reason, author and timestamp — its subtotal is in
 *    the rows and must not be in the total. Any renderer that re-sums the
 *    column instead of reading `invoice.totals` fails on this row alone.
 *  - A line with NO valid fee, which is `feeSource: null` and a blocking
 *    validation.
 *  - `slaPerformancePercent: null` — no measurable job — which must print as a
 *    dash and never as 0%.
 *  - An empty `specialProjects`, which the contract says omits the section.
 *  - A site called "Smith & Co. (UK)/EU — Ünit 3" and a note containing a
 *    literal `<`, both of which corrupt an OOXML package if a writer forgets to
 *    escape, and a filename if `exportFilename` forgets to sanitise.
 *  - An `internalNote`, which must appear in the preview and the workbook and
 *    must NOT appear in the Word file or the PDF.
 */

import type { CombinedReportPayload } from "../reporting/contract";

export const SAMPLE_PERIOD = {
  start: "2026-03-01",
  end: "2026-03-31",
  label: "March 2026",
  partialMonth: false,
} as const;

export function samplePayload(): CombinedReportPayload {
  return {
    schemaVersion: 1,
    generatedAt: "2026-04-02T09:15:00.000Z",
    organisationId: "org-maintsupp",
    organisationName: "MAINTSUPP",
    period: { ...SAMPLE_PERIOD },
    previousPeriod: {
      start: "2026-02-01",
      end: "2026-02-28",
      label: "February 2026",
      partialMonth: false,
    },
    invoice: {
      invoiceId: "inv-fixture-1",
      invoiceNumber: "MS-000241",
      status: "Ready for Review",
      invoiceDate: "2026-04-01",
      dueAt: "2026-05-01",
      servicePeriod: { ...SAMPLE_PERIOD },
      clientName: "Smith & Co. (UK)/EU — Ünit 3",
      billingAddress: "12 Bridge Street, Manchester, M1 1AA",
      clientReference: "SC-2026-Q1",
      purchaseOrder: "PO-88421",
      internalReference: "INT/MAR/26",
      currency: "GBP",
      paymentTerms: "30 days from invoice date",
      vatEnabled: true,
      vatRateBasisPoints: 2000,
      vatNumber: "GB 123 4567 89",
      clientNote: "Fee covers reactive coordination and compliance oversight for the period.",
      internalNote: "Chase the fee override for Leeds Central before April — <not for the client>.",
      lines: [
        {
          lineNo: 1,
          siteId: "site-1",
          siteName: "Manchester Piccadilly",
          siteReference: "MCR-01",
          activeStatus: "Active",
          activeFrom: "2024-06-01",
          activeTo: null,
          billable: true,
          feePence: 12_500,
          feeSource: "Client fee",
          feeRecordId: "fee-client-1",
          vatRateBasisPoints: 2000,
          lineSubtotalPence: 12_500,
          lineVatPence: 2_500,
          lineTotalPence: 15_000,
          included: true,
          exclusionReason: null,
          excludedByEmail: null,
          excludedAt: null,
          validation: [],
        },
        {
          lineNo: 2,
          siteId: "site-2",
          siteName: "Leeds Central",
          siteReference: "LDS-02",
          activeStatus: "Active",
          activeFrom: "2025-01-15",
          activeTo: null,
          billable: true,
          feePence: 17_500,
          feeSource: "Site override",
          feeRecordId: "fee-override-2",
          vatRateBasisPoints: 2000,
          lineSubtotalPence: 17_500,
          lineVatPence: 3_500,
          lineTotalPence: 21_000,
          included: true,
          exclusionReason: null,
          excludedByEmail: null,
          excludedAt: null,
          validation: [
            {
              severity: "info",
              code: "FEE_OVERRIDE",
              message: "This site carries an override above the client fee.",
            },
          ],
        },
        {
          lineNo: 3,
          siteId: "site-3",
          siteName: "Birmingham New Street",
          siteReference: "BHM-03",
          activeStatus: "Active",
          activeFrom: "2023-09-01",
          activeTo: null,
          billable: true,
          feePence: 12_500,
          feeSource: "Client fee",
          feeRecordId: "fee-client-1",
          vatRateBasisPoints: 2000,
          lineSubtotalPence: 12_500,
          lineVatPence: 2_500,
          lineTotalPence: 15_000,
          included: true,
          exclusionReason: null,
          excludedByEmail: null,
          excludedAt: null,
          validation: [],
        },
        {
          lineNo: 4,
          siteId: "site-4",
          siteName: "Glasgow Queen Street",
          siteReference: "GLA-04",
          activeStatus: "Active",
          activeFrom: "2025-11-01",
          activeTo: "2026-03-14",
          billable: true,
          feePence: 12_500,
          feeSource: "Client fee",
          feeRecordId: "fee-client-1",
          vatRateBasisPoints: 2000,
          lineSubtotalPence: 12_500,
          lineVatPence: 2_500,
          lineTotalPence: 15_000,
          included: false,
          exclusionReason: "Site handed back mid-period; fee waived by agreement.",
          excludedByEmail: "owner@maintsupp.example",
          excludedAt: "2026-04-01T16:04:00.000Z",
          validation: [
            {
              severity: "warning",
              code: "PART_PERIOD",
              message: "Active for part of the period only.",
            },
          ],
        },
        {
          lineNo: 5,
          siteId: "site-5",
          siteName: "Cardiff Queen Street",
          siteReference: null,
          activeStatus: "Active",
          activeFrom: "2026-02-20",
          activeTo: null,
          billable: true,
          feePence: 0,
          feeSource: null,
          feeRecordId: null,
          vatRateBasisPoints: 2000,
          lineSubtotalPence: 0,
          lineVatPence: 0,
          lineTotalPence: 0,
          included: true,
          exclusionReason: null,
          excludedByEmail: null,
          excludedAt: null,
          validation: [
            {
              severity: "blocking",
              code: "NO_FEE",
              message: "No site, client or organisation fee applies to this site.",
            },
          ],
        },
      ],
      adjustments: [
        {
          id: "adj-1",
          kind: "credit",
          amountPence: 2_500,
          reason: "Goodwill credit for the February portal outage.",
          authorisedByEmail: "owner@maintsupp.example",
          createdAt: "2026-04-01T15:40:00.000Z",
        },
      ],
      totals: {
        totalSites: 5,
        includedSites: 4,
        excludedSites: 1,
        // Lines 1, 2, 3 and 5 — the excluded Glasgow line is NOT in this figure.
        subtotalPence: 42_500,
        vatPence: 8_500,
        adjustmentPence: 0,
        creditPence: 2_500,
        totalPence: 48_500,
        // Null on purpose: 12,500 / 17,500 / 12,500 / 0 are not one fee.
        singleFeePence: null,
        averageFeePence: 10_625,
      },
    },
    maintenance: {
      kpis: {
        jobsRecorded: 9,
        completedJobs: 5,
        openJobs: 3,
        openJobsPastTarget: 2,
        slaPerformancePercent: 80,
        jobsOnHold: 1,
        criticalOpenJobs: 1,
        completedMaintenanceSpendPence: 486_000,
      },
      executive: {
        counts: {
          totalJobs: 9,
          activeSites: 5,
          sitesWithJobs: 4,
          completedJobs: 5,
          openJobs: 3,
          cancelledJobs: 1,
          measurableJobs: 5,
          withinSla: 4,
          outsideSla: 1,
          slaPercent: 80,
          jobsWithApprovedHolds: 1,
          openPastTarget: 2,
          criticalOpen: 1,
          previousTotalJobs: 12,
        },
        narrative: [
          "Nine jobs were recorded across four of the five active sites in March 2026, down from twelve in the equivalent previous period.",
          "Five jobs completed at a recorded cost of £4,860.00; three remain open, two of them past their target date.",
          "Four of the five measurable jobs closed inside their SLA target, an SLA performance of 80%.",
        ],
      },
      siteSummary: [
        {
          siteId: "site-1",
          siteName: "Manchester Piccadilly",
          jobsRaised: 4,
          completed: 3,
          open: 1,
          cancelled: 0,
          onHold: 0,
          pastTarget: 1,
          critical: 0,
          completedCostPence: 268_000,
          openQuotedCostPence: 45_000,
          fixedServiceFeePence: 12_500,
          billable: true,
        },
        {
          siteId: "site-2",
          siteName: "Leeds Central",
          jobsRaised: 3,
          completed: 1,
          open: 1,
          cancelled: 1,
          onHold: 1,
          pastTarget: 1,
          critical: 1,
          completedCostPence: 158_000,
          openQuotedCostPence: 120_000,
          fixedServiceFeePence: 17_500,
          billable: true,
        },
        {
          siteId: "site-3",
          siteName: "Birmingham New Street",
          jobsRaised: 1,
          completed: 1,
          open: 0,
          cancelled: 0,
          onHold: 0,
          pastTarget: 0,
          critical: 0,
          completedCostPence: 60_000,
          openQuotedCostPence: 0,
          fixedServiceFeePence: 12_500,
          billable: true,
        },
        {
          siteId: "site-4",
          siteName: "Glasgow Queen Street",
          jobsRaised: 1,
          completed: 0,
          open: 1,
          cancelled: 0,
          onHold: 0,
          pastTarget: 0,
          critical: 0,
          completedCostPence: 0,
          openQuotedCostPence: 18_000,
          fixedServiceFeePence: 0,
          billable: false,
        },
      ],
      siteSummaryTotals: {
        jobsRaised: 9,
        completed: 5,
        open: 3,
        cancelled: 1,
        onHold: 1,
        pastTarget: 2,
        critical: 1,
        completedCostPence: 486_000,
        openQuotedCostPence: 183_000,
        fixedServiceFeePence: 42_500,
      },
      spend: {
        serviceFeePence: 48_500,
        completedMaintenancePence: 486_000,
        openCommittedPence: 183_000,
        projectPence: 120_000,
        routinePence: 148_000,
        previousCompletedMaintenancePence: 512_000,
      },
      sla: [
        {
          requestId: "job-1",
          reference: "MN-1201",
          siteName: "Manchester Piccadilly",
          description: "Roof leak above the stockroom",
          classification: "Reactive — urgent",
          targetWorkingDays: 2,
          elapsedWorkingDays: 2,
          approvedHoldDays: 0,
          adjustedWorkingDays: 2,
          result: "Within",
          exclusionReason: null,
        },
        {
          requestId: "job-2",
          reference: "MN-1202",
          siteName: "Leeds Central",
          description: "Cold store compressor failure",
          classification: "Reactive — critical",
          targetWorkingDays: 1,
          elapsedWorkingDays: 6,
          approvedHoldDays: 3,
          adjustedWorkingDays: 3,
          result: "Outside",
          exclusionReason: null,
        },
        {
          requestId: "job-3",
          reference: "MN-1203",
          siteName: "Birmingham New Street",
          description: "Annual fire alarm inspection",
          classification: "Compliance",
          targetWorkingDays: 10,
          elapsedWorkingDays: 7,
          approvedHoldDays: 0,
          adjustedWorkingDays: 7,
          result: "Within",
          exclusionReason: null,
        },
        {
          requestId: "job-4",
          reference: "MN-1204",
          siteName: "Manchester Piccadilly",
          description: "Shopfront glazing replacement",
          classification: "Reactive — standard",
          targetWorkingDays: 5,
          elapsedWorkingDays: 4,
          approvedHoldDays: 0,
          adjustedWorkingDays: 4,
          result: "Within",
          exclusionReason: null,
        },
        {
          requestId: "job-5",
          reference: "MN-1205",
          siteName: "Manchester Piccadilly",
          description: "Air conditioning service",
          classification: "Planned",
          targetWorkingDays: 15,
          elapsedWorkingDays: 9,
          approvedHoldDays: 0,
          adjustedWorkingDays: 9,
          result: "Within",
          exclusionReason: null,
        },
        {
          requestId: "job-9",
          reference: "MN-1209",
          siteName: "Leeds Central",
          description: "Signage damaged in storm",
          classification: null,
          targetWorkingDays: null,
          elapsedWorkingDays: 3,
          approvedHoldDays: 0,
          adjustedWorkingDays: null,
          result: "Excluded",
          exclusionReason: "No SLA classification is set on this job, so no target applies.",
        },
      ],
      holds: [
        {
          holdId: "hold-1",
          requestId: "job-2",
          reference: "MN-1202",
          siteName: "Leeds Central",
          description: "Cold store compressor failure",
          classification: "Reactive — critical",
          targetWorkingDays: 1,
          elapsedWorkingDays: 6,
          approvedHoldDays: 3,
          adjustedWorkingDays: 3,
          slaResult: "Outside",
          reason: "Compressor on back order from the manufacturer",
          category: "Awaiting parts",
          startAt: "2026-03-09",
          endAt: "2026-03-12",
          approved: true,
          approvedBy: "operations@maintsupp.example",
          approvalDate: "2026-03-09",
          note: "Client agreed to a temporary chiller in the interim.",
        },
      ],
      openPastTarget: [
        {
          requestId: "job-6",
          reference: "MN-1206",
          siteName: "Manchester Piccadilly",
          issue: "Car park lighting column unstable",
          priority: "High",
          classification: "Reactive — standard",
          raisedOn: "2026-03-05",
          targetOn: "2026-03-12",
          workingDaysOpen: 19,
          daysPastTarget: 12,
          status: "In Progress",
          contractor: "Northern Electrical Ltd",
          blocker: "Structural survey outstanding",
          nextAction: "Chase survey report",
          responsibleUser: "operations@maintsupp.example",
        },
        {
          requestId: "job-7",
          reference: "MN-1207",
          siteName: "Leeds Central",
          issue: "Fire door closer failed on the service corridor",
          priority: "Critical",
          classification: "Compliance",
          raisedOn: "2026-03-18",
          targetOn: "2026-03-20",
          workingDaysOpen: 9,
          daysPastTarget: 7,
          status: "Awaiting Approval",
          contractor: null,
          blocker: "Quote above the approval threshold",
          nextAction: "Client sign-off on the quote",
          responsibleUser: "operations@maintsupp.example",
        },
      ],
      criticalOpen: [
        {
          requestId: "job-7",
          reference: "MN-1207",
          siteName: "Leeds Central",
          issue: "Fire door closer failed on the service corridor",
          priority: "Critical",
          classification: "Compliance",
          raisedOn: "2026-03-18",
          targetOn: "2026-03-20",
          workingDaysOpen: 9,
          daysPastTarget: 7,
          status: "Awaiting Approval",
          contractor: null,
          blocker: "Quote above the approval threshold",
          nextAction: "Client sign-off on the quote",
          responsibleUser: "operations@maintsupp.example",
        },
      ],
      // Empty on purpose — the contract says the section is then omitted.
      specialProjects: [],
      jobLog: [
        {
          group: "In Progress",
          rows: [
            {
              requestId: "job-6",
              reference: "MN-1206",
              siteName: "Manchester Piccadilly",
              issue: "Car park lighting column unstable",
              jobType: "Electrical",
              classification: "Reactive — standard",
              priority: "High",
              raisedOn: "2026-03-05",
              targetOn: "2026-03-12",
              completedOn: null,
              status: "In Progress",
              slaResult: null,
              contractor: "Northern Electrical Ltd",
              recordedCostPence: null,
              quotedCostPence: 45_000,
              holdDays: 0,
              notes: "Survey booked for the first week of April.",
            },
          ],
        },
        {
          group: "Awaiting Approval",
          rows: [
            {
              requestId: "job-7",
              reference: "MN-1207",
              siteName: "Leeds Central",
              issue: "Fire door closer failed on the service corridor",
              jobType: "Fire safety",
              classification: "Compliance",
              priority: "Critical",
              raisedOn: "2026-03-18",
              targetOn: "2026-03-20",
              completedOn: null,
              status: "Awaiting Approval",
              slaResult: null,
              contractor: null,
              recordedCostPence: null,
              quotedCostPence: 120_000,
              holdDays: 0,
              notes: null,
            },
          ],
        },
        {
          group: "On Hold",
          rows: [
            {
              requestId: "job-8",
              reference: "MN-1208",
              siteName: "Glasgow Queen Street",
              issue: "Shutter motor intermittent",
              jobType: "Mechanical",
              classification: "Reactive — standard",
              priority: "Medium",
              raisedOn: "2026-03-22",
              targetOn: "2026-03-27",
              completedOn: null,
              status: "On Hold",
              slaResult: null,
              contractor: "Clyde Shutters",
              recordedCostPence: null,
              quotedCostPence: 18_000,
              holdDays: 4,
              notes: "Access restricted until the handover completes.",
            },
          ],
        },
        {
          group: "Completed",
          rows: [
            {
              requestId: "job-1",
              reference: "MN-1201",
              siteName: "Manchester Piccadilly",
              issue: "Roof leak above the stockroom",
              jobType: "Fabric",
              classification: "Reactive — urgent",
              priority: "High",
              raisedOn: "2026-03-02",
              targetOn: "2026-03-04",
              completedOn: "2026-03-04",
              status: "Completed",
              slaResult: "Within",
              contractor: "Pennine Roofing",
              recordedCostPence: 128_000,
              quotedCostPence: 130_000,
              holdDays: 0,
              notes: null,
            },
            {
              requestId: "job-2",
              reference: "MN-1202",
              siteName: "Leeds Central",
              issue: "Cold store compressor failure",
              jobType: "Refrigeration",
              classification: "Reactive — critical",
              priority: "Critical",
              raisedOn: "2026-03-06",
              targetOn: "2026-03-09",
              completedOn: "2026-03-16",
              status: "Completed",
              slaResult: "Outside",
              contractor: "Yorkshire Cooling",
              recordedCostPence: 158_000,
              quotedCostPence: 150_000,
              holdDays: 3,
              notes: "Held three working days awaiting a compressor.",
            },
            {
              requestId: "job-3",
              reference: "MN-1203",
              siteName: "Birmingham New Street",
              issue: "Annual fire alarm inspection",
              jobType: "Fire safety",
              classification: "Compliance",
              priority: "Medium",
              raisedOn: "2026-03-03",
              targetOn: "2026-03-17",
              completedOn: "2026-03-12",
              status: "Completed",
              slaResult: "Within",
              contractor: "Midland Fire",
              recordedCostPence: 60_000,
              quotedCostPence: 60_000,
              holdDays: 0,
              notes: null,
            },
            {
              requestId: "job-4",
              reference: "MN-1204",
              siteName: "Manchester Piccadilly",
              issue: "Shopfront glazing replacement",
              jobType: "Fabric",
              classification: "Reactive — standard",
              priority: "Medium",
              raisedOn: "2026-03-10",
              targetOn: "2026-03-17",
              completedOn: "2026-03-16",
              status: "Completed",
              slaResult: "Within",
              contractor: "Pennine Glazing",
              recordedCostPence: 88_000,
              quotedCostPence: 90_000,
              holdDays: 0,
              notes: null,
            },
            {
              requestId: "job-5",
              reference: "MN-1205",
              siteName: "Manchester Piccadilly",
              issue: "Air conditioning service",
              jobType: "Mechanical",
              classification: "Planned",
              priority: "Low",
              raisedOn: "2026-03-11",
              targetOn: "2026-04-01",
              completedOn: "2026-03-24",
              status: "Completed",
              slaResult: "Within",
              contractor: "Airflow Services",
              recordedCostPence: 52_000,
              quotedCostPence: 52_000,
              holdDays: 0,
              notes: null,
            },
          ],
        },
        {
          group: "Cancelled",
          rows: [
            {
              requestId: "job-10",
              reference: "MN-1210",
              siteName: "Leeds Central",
              issue: "Duplicate report of the compressor fault",
              jobType: "Refrigeration",
              classification: null,
              priority: "Low",
              raisedOn: "2026-03-07",
              targetOn: null,
              completedOn: null,
              status: "Cancelled",
              slaResult: null,
              contractor: null,
              recordedCostPence: null,
              quotedCostPence: null,
              holdDays: 0,
              notes: "Duplicate of MN-1202.",
            },
          ],
        },
      ],
      dataQuality: [
        {
          severity: "blocking",
          code: "NO_FEE",
          message: "Cardiff Queen Street has no site, client or organisation fee.",
          entityType: "site",
          entityId: "site-5",
          href: "/dashboard/stores?site=site-5",
        },
        {
          severity: "warning",
          code: "MISSING_COST",
          message: "MN-1206 is past target with no quoted or recorded cost.",
          entityType: "job",
          entityId: "job-6",
          href: "/dashboard/jobs?item=job-6",
        },
        {
          severity: "info",
          code: "NO_CLASSIFICATION",
          message: "MN-1209 has no SLA classification and was excluded from the measurement.",
          entityType: "job",
          entityId: "job-9",
          href: "/dashboard/jobs?item=job-9",
        },
      ],
      slaRules: [
        { classification: "Reactive — critical", targetWorkingDays: 1, version: 3, note: "Escalates to the duty manager at 24 hours." },
        { classification: "Reactive — urgent", targetWorkingDays: 2, version: 3, note: null },
        { classification: "Reactive — standard", targetWorkingDays: 5, version: 3, note: null },
        { classification: "Compliance", targetWorkingDays: 10, version: 2, note: "Statutory inspections excluded from hold adjustment." },
        { classification: "Planned", targetWorkingDays: 15, version: 2, note: null },
      ],
    },
  };
}

/**
 * The other extreme: a period in which nothing happened.
 *
 * An empty portfolio is the state most likely to make a renderer print a
 * confident falsehood — "£0 spent", "0% SLA performance" — so it is a fixture
 * rather than an afterthought. `slaPerformancePercent` is null and not zero,
 * and every table is empty and must show its own sentence.
 */
export function emptyPayload(): CombinedReportPayload {
  return {
    schemaVersion: 1,
    generatedAt: "2026-04-02T09:15:00.000Z",
    organisationId: "org-maintsupp",
    organisationName: "MAINTSUPP",
    period: { start: "2026-03-01", end: "2026-03-31", label: "March 2026", partialMonth: false },
    previousPeriod: null,
    invoice: {
      invoiceId: null,
      invoiceNumber: null,
      status: "Draft",
      invoiceDate: null,
      dueAt: null,
      servicePeriod: { start: "2026-03-01", end: "2026-03-31", label: "March 2026", partialMonth: false },
      clientName: "Quiet Estates Ltd",
      billingAddress: null,
      clientReference: null,
      purchaseOrder: null,
      internalReference: null,
      currency: "GBP",
      paymentTerms: null,
      vatEnabled: false,
      vatRateBasisPoints: 0,
      vatNumber: null,
      clientNote: null,
      internalNote: null,
      lines: [],
      adjustments: [],
      totals: {
        totalSites: 0,
        includedSites: 0,
        excludedSites: 0,
        subtotalPence: 0,
        vatPence: 0,
        adjustmentPence: 0,
        creditPence: 0,
        totalPence: 0,
        singleFeePence: null,
        averageFeePence: 0,
      },
    },
    maintenance: {
      kpis: {
        jobsRecorded: 0,
        completedJobs: 0,
        openJobs: 0,
        openJobsPastTarget: 0,
        slaPerformancePercent: null,
        jobsOnHold: 0,
        criticalOpenJobs: 0,
        completedMaintenanceSpendPence: 0,
      },
      executive: {
        counts: {
          totalJobs: 0,
          activeSites: 0,
          sitesWithJobs: 0,
          completedJobs: 0,
          openJobs: 0,
          cancelledJobs: 0,
          measurableJobs: 0,
          withinSla: 0,
          outsideSla: 0,
          slaPercent: null,
          jobsWithApprovedHolds: 0,
          openPastTarget: 0,
          criticalOpen: 0,
          previousTotalJobs: null,
        },
        narrative: ["No job was recorded in March 2026."],
      },
      siteSummary: [],
      siteSummaryTotals: {
        jobsRaised: 0,
        completed: 0,
        open: 0,
        cancelled: 0,
        onHold: 0,
        pastTarget: 0,
        critical: 0,
        completedCostPence: 0,
        openQuotedCostPence: 0,
        fixedServiceFeePence: 0,
      },
      spend: {
        serviceFeePence: 0,
        completedMaintenancePence: 0,
        openCommittedPence: 0,
        projectPence: 0,
        routinePence: 0,
        previousCompletedMaintenancePence: null,
      },
      sla: [],
      holds: [],
      openPastTarget: [],
      criticalOpen: [],
      specialProjects: [],
      jobLog: [],
      dataQuality: [],
      slaRules: [],
    },
  };
}
